/**
 * report/nodes/report-formatting.ts
 * 
 * THE POLISHER.
 * 
 * Formats all sections into final Markdown report.
 * Ensures consistent structure, proper citations, and clean formatting.
 * 
 * Core principle: PRESENTATION MATTERS.
 * A well-formatted report is easier to read and understand.
 */

import { createLogger } from '../../observability/logger.js'
import type { GraphNode, ReportState, NodeResult, FormattedReport, ReportSection, ReportMetadata } from '../types.js'

const log = createLogger('report:formatting')

export class ReportFormattingNode implements GraphNode {
  type = 'ReportFormatting' as const

  async execute(state: ReportState): Promise<NodeResult> {
    log.info('Formatting final report', { 
      topic: state.topic,
      sectionCount: state.sections.length,
    })

    try {
      const report = this.formatReport(state)
      
      state.finalReport = report.markdown
      state.metadata.completedAt = Date.now()

      return {
        success: true,
        nextNode: 'complete',
        message: `Report formatted: ${report.wordCount} words, ${report.sectionCount} sections`,
      }
    } catch (err) {
      log.error('Formatting failed', { error: String(err) })
      return {
        success: false,
        nextNode: 'ReportFormatting',
        message: `Formatting failed: ${err}`,
      }
    }
  }

  private formatReport(state: ReportState): FormattedReport {
    const { topic, sections, metadata } = state
    
    const parts: string[] = []
    
    // Title and metadata
    parts.push(this.formatTitle(topic))
    parts.push(this.formatMetadata(metadata))
    
    // Table of contents
    parts.push(this.formatTableOfContents(sections))
    
    // Sections
    for (const section of sections) {
      parts.push(this.formatSection(section))
    }
    
    // References
    parts.push(this.formatReferences(sections))
    
    // Footer
    parts.push(this.formatFooter(metadata))
    
    const markdown = parts.join('\n\n')
    const wordCount = this.countWords(markdown)
    
    return {
      markdown,
      wordCount,
      sectionCount: sections.length,
    }
  }

  private formatTitle(topic: string): string {
    return `# ${topic}\n\n*Generated by Conway Automaton Report System*`
  }

  private formatMetadata(metadata: ReportMetadata): string {
    const duration = metadata.completedAt 
      ? Math.round((metadata.completedAt - metadata.startedAt) / 1000)
      : 0
    
    return [
      '---',
      `**Generated:** ${new Date(metadata.startedAt).toISOString()}`,
      `**Duration:** ${duration}s`,
      `**Sections:** ${metadata.totalSections}`,
      `**Sources:** ${metadata.totalSources}`,
      `**Reflections:** ${metadata.totalReflections}`,
      '---',
    ].join('\n')
  }

  private formatTableOfContents(sections: ReportSection[]): string {
    const lines = ['## Table of Contents\n']
    
    for (let i = 0; i < sections.length; i++) {
      const section = sections[i]
      lines.push(`${i + 1}. [${section.title}](#${section.id})`)
    }
    
    return lines.join('\n')
  }

  private formatSection(section: ReportSection): string {
    const lines: string[] = []
    
    // Section header with anchor
    lines.push(`## <a id="${section.id}"></a>${section.title}\n`)
    
    // Content
    if (section.content) {
      lines.push(section.content)
    } else {
      lines.push('*No content available for this section.*')
    }
    
    return lines.join('\n')
  }

  private formatReferences(sections: ReportSection[]): string {
    const lines = ['## References\n']
    const allSources = new Map<string, { url: string; title: string }>()
    
    // Collect all unique sources
    for (const section of sections) {
      for (const source of section.sources) {
        if (!allSources.has(source.url)) {
          allSources.set(source.url, { url: source.url, title: source.title })
        }
      }
    }
    
    // Format references
    let refNum = 1
    for (const [, source] of allSources) {
      lines.push(`${refNum}. [${source.title}](${source.url})`)
      refNum++
    }
    
    return lines.join('\n')
  }

  private formatFooter(metadata: ReportMetadata): string {
    return [
      '---',
      '*This report was generated by the Conway Automaton Report System.*',
      '*For more information, visit [conway.tech](https://conway.tech)*',
    ].join('\n')
  }

  private countWords(text: string): number {
    return text.split(/\s+/).filter(word => word.length > 0).length
  }
}
